---
name: bibcop
'on':
  push:
  pull_request:
jobs:
  bibcop:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: yegor256/bibcop-action@master
