# SPDX-FileCopyrightText: Copyright (c) 2024-2026 Yegor Bugayenko
# SPDX-License-Identifier: MIT
---
# yamllint disable rule:line-length
name: latexmk
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
concurrency:
  group: latexmk-${{ github.ref }}
  cancel-in-progress: true
jobs:
  latexmk:
    timeout-minutes: 15
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v7
        with:
          submodules: true
      - uses: yegor256/latexmk-action@0.20.0
        with:
          opts: -pdf
          depends: DEPENDS.txt
      - if: github.event_name == 'push'
        run: mkdir -p gh-pages && cp paper.pdf gh-pages/paper.pdf
      - if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v4.1.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: gh-pages
          keep_files: true
